version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1
      semver-major-days: 1
      semver-minor-days: 1
      semver-patch-days: 1
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
