// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForNewPackages() {
  return window['go']['main']['App']['CheckForNewPackages']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckHomebrewUpdate() {
  return window['go']['main']['App']['CheckHomebrewUpdate']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportBrewfile(arg1) {
  return window['go']['main']['App']['ExportBrewfile'](arg1);
}

export function GetAllBrewPackages() {
  return window['go']['main']['App']['GetAllBrewPackages']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBrewCasks() {
  return window['go']['main']['App']['GetBrewCasks']();
}

export function GetBrewCleanupDryRun() {
  return window['go']['main']['App']['GetBrewCleanupDryRun']();
}

export function GetBrewLeaves() {
  return window['go']['main']['App']['GetBrewLeaves']();
}

export function GetBrewPackageInfo(arg1) {
  return window['go']['main']['App']['GetBrewPackageInfo'](arg1);
}

export function GetBrewPackageInfoAsJson(arg1) {
  return window['go']['main']['App']['GetBrewPackageInfoAsJson'](arg1);
}

export function GetBrewPackages() {
  return window['go']['main']['App']['GetBrewPackages']();
}

export function GetBrewPath() {
  return window['go']['main']['App']['GetBrewPath']();
}

export function GetBrewTapInfo(arg1) {
  return window['go']['main']['App']['GetBrewTapInfo'](arg1);
}

export function GetBrewTaps() {
  return window['go']['main']['App']['GetBrewTaps']();
}

export function GetBrewUpdatablePackages() {
  return window['go']['main']['App']['GetBrewUpdatablePackages']();
}

export function GetCurrentLanguage() {
  return window['go']['main']['App']['GetCurrentLanguage']();
}

export function GetDeprecatedFormulae(arg1) {
  return window['go']['main']['App']['GetDeprecatedFormulae'](arg1);
}

export function GetHomebrewVersion() {
  return window['go']['main']['App']['GetHomebrewVersion']();
}

export function GetMirrorSource() {
  return window['go']['main']['App']['GetMirrorSource']();
}

export function GetSessionLogs() {
  return window['go']['main']['App']['GetSessionLogs']();
}

export function InstallBrewPackage(arg1) {
  return window['go']['main']['App']['InstallBrewPackage'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseNewPackagesFromUpdateOutput(arg1) {
  return window['go']['main']['App']['ParseNewPackagesFromUpdateOutput'](arg1);
}

export function RemoveBrewPackage(arg1) {
  return window['go']['main']['App']['RemoveBrewPackage'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RunBrewCleanup() {
  return window['go']['main']['App']['RunBrewCleanup']();
}

export function RunBrewDoctor() {
  return window['go']['main']['App']['RunBrewDoctor']();
}

export function SetBrewPath(arg1) {
  return window['go']['main']['App']['SetBrewPath'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetMirrorSource(arg1, arg2) {
  return window['go']['main']['App']['SetMirrorSource'](arg1, arg2);
}

export function TapBrewRepository(arg1) {
  return window['go']['main']['App']['TapBrewRepository'](arg1);
}

export function UntapBrewRepository(arg1) {
  return window['go']['main']['App']['UntapBrewRepository'](arg1);
}

export function UpdateAllBrewPackages() {
  return window['go']['main']['App']['UpdateAllBrewPackages']();
}

export function UpdateBrewDatabase() {
  return window['go']['main']['App']['UpdateBrewDatabase']();
}

export function UpdateBrewDatabaseWithOutput() {
  return window['go']['main']['App']['UpdateBrewDatabaseWithOutput']();
}

export function UpdateBrewPackage(arg1) {
  return window['go']['main']['App']['UpdateBrewPackage'](arg1);
}

export function UpdateHomebrew() {
  return window['go']['main']['App']['UpdateHomebrew']();
}

export function UpdateSelectedBrewPackages(arg1) {
  return window['go']['main']['App']['UpdateSelectedBrewPackages'](arg1);
}
