// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBrewPackageInfo(arg1) {
  return window['go']['main']['App']['GetBrewPackageInfo'](arg1);
}

export function GetBrewPackageInfoAsJson(arg1) {
  return window['go']['main']['App']['GetBrewPackageInfoAsJson'](arg1);
}

export function GetBrewPackages() {
  return window['go']['main']['App']['GetBrewPackages']();
}

export function GetBrewUpdatablePackages() {
  return window['go']['main']['App']['GetBrewUpdatablePackages']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveBrewPackage(arg1) {
  return window['go']['main']['App']['RemoveBrewPackage'](arg1);
}

export function UpdateBrewPackage(arg1) {
  return window['go']['main']['App']['UpdateBrewPackage'](arg1);
}
