// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {brew} from '../models';
import {main} from '../models';
import {context} from '../models';

export function CheckForNewPackages():Promise<brew.NewPackagesInfo>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CheckHomebrewUpdate():Promise<Record<string, any>>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function ExportBrewfile(arg1:string):Promise<void>;

export function GetAllBrewPackages():Promise<Array<any>>;

export function GetAppVersion():Promise<string>;

export function GetBrewCaskSizes(arg1:Array<string>):Promise<Record<string, string>>;

export function GetBrewCasks():Promise<Array<any>>;

export function GetBrewCleanupDryRun():Promise<string>;

export function GetBrewLeaves():Promise<Array<string>>;

export function GetBrewPackageInfo(arg1:string):Promise<string>;

export function GetBrewPackageInfoAsJson(arg1:string):Promise<Record<string, any>>;

export function GetBrewPackageSizes(arg1:Array<string>):Promise<Record<string, string>>;

export function GetBrewPackages():Promise<Array<any>>;

export function GetBrewPath():Promise<string>;

export function GetBrewTapInfo(arg1:string):Promise<string>;

export function GetBrewTaps():Promise<Array<any>>;

export function GetBrewUpdatablePackages():Promise<Array<any>>;

export function GetCaskAppDir():Promise<string>;

export function GetContext():Promise<context.Context>;

export function GetCurrentLanguage():Promise<string>;

export function GetDeprecatedFormulae(arg1:string):Promise<Array<string>>;

export function GetHomebrewCaskVersion():Promise<string>;

export function GetHomebrewVersion():Promise<string>;

export function GetMirrorSource():Promise<Record<string, string>>;

export function GetOutdatedFlag():Promise<string>;

export function GetSessionLogs():Promise<string>;

export function GetTranslation(arg1:string,arg2:Record<string, string>):Promise<string>;

export function InstallBrewPackage(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseNewPackagesFromUpdateOutput(arg1:string):Promise<brew.NewPackagesInfo>;

export function RemoveBrewPackage(arg1:string):Promise<string>;

export function RestartApp():Promise<void>;

export function RunBrewCleanup():Promise<string>;

export function RunBrewDoctor():Promise<string>;

export function SelectCaskAppDir():Promise<string>;

export function SetBrewPath(arg1:string):Promise<void>;

export function SetCaskAppDir(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMirrorSource(arg1:string,arg2:string):Promise<void>;

export function SetOutdatedFlag(arg1:string):Promise<void>;

export function TapBrewRepository(arg1:string):Promise<string>;

export function UntapBrewRepository(arg1:string):Promise<string>;

export function UpdateAllBrewPackages():Promise<string>;

export function UpdateBrewDatabase():Promise<void>;

export function UpdateBrewDatabaseWithOutput():Promise<string>;

export function UpdateBrewPackage(arg1:string):Promise<string>;

export function UpdateHomebrew():Promise<string>;

export function UpdateSelectedBrewPackages(arg1:Array<string>):Promise<string>;
