// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GetAllBrewPackages():Promise<Array<any>>;

export function GetAppVersion():Promise<string>;

export function GetBrewLeaves():Promise<Array<string>>;

export function GetBrewPackageInfo(arg1:string):Promise<string>;

export function GetBrewPackageInfoAsJson(arg1:string):Promise<Record<string, any>>;

export function GetBrewPackages():Promise<Array<any>>;

export function GetBrewTaps():Promise<Array<any>>;

export function GetBrewUpdatablePackages():Promise<Array<any>>;

export function GetCurrentLanguage():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveBrewPackage(arg1:string):Promise<string>;

export function RunBrewCleanup():Promise<string>;

export function RunBrewDoctor():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function UpdateAllBrewPackages():Promise<string>;

export function UpdateBrewPackage(arg1:string):Promise<string>;
