// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBrewPackageInfo(arg1:string):Promise<Record<string, any>>;

export function GetBrewPackages():Promise<Array<any>>;

export function GetBrewUpdatablePackages():Promise<Array<any>>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveBrewPackage(arg1:string):Promise<string>;

export function UpdateBrewPackage(arg1:string):Promise<string>;
